### ISSUE TITLE
terra/gdal

### ISSUE THREAD

**Issue by johannajokio** [milos-agathon/make-your-3d-city#1]
Hi. I  get an issue installing terra on Linux (R studio):

_Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):  unable to load shared object '/.../R/x86_64-pc-linux-gnu-library/4.3/terra/libs/terra.so':   libgdal.so.32: cannot open shared object file: No such file or directory_

this may be a known issue related to gdal but I was wondering how you might solve it?

**Comment by milos-agathon** [comment]
Hey, sorry to hear that. I never installed terra on Linux or in RStudio so can't help you with that. Perhaps the best approach is to open the issue in the terra GitHub repo

**Comment by johannajokio** [comment]
Yeah. With the spatial packages you tend to end up in dependency hell. So  I did 

install.packages('terra', repos='https://rspatial.r-universe.dev')
library(terra)

library(remotes)
install_github("r-spatial/sf")
library(sf)
