### ISSUE TITLE
Not rendering as expected

### ISSUE THREAD

**Issue by lbarqueira** [milos-agathon/make-your-3d-city#2]
Hi Milos,

thank you for sharing the code.

While reproducing your code as-is, I obtained at Point 6 (Render) the following (snapshot):

![milos_issue_github](https://github.com/milos-agathon/make-your-3d-city/assets/65919567/a08ca327-18ad-4873-bdee-aba4ef588e07)

I have reproduced your code exactly as it is.

I can not understand the reason for the black portion of the image. 

Notice also, than the image (png) that is saved in 4. SAVE ORTHO AS IMAGE, is as following:

![binnenhof](https://github.com/milos-agathon/make-your-3d-city/assets/65919567/adc9cb39-cd80-43be-bc5a-723853209091)

Could you please help me identify this issue?

Thank you very much,

Luis Barqueira

**Comment by milos-agathon** [comment]
Hi Luis, thanks for sharing this issue with me.
I think this has to do with the latest version of rayshader that you're using.
Could you downgrade your rayshader to the previous version?

**Comment by lbarqueira** [comment]
Hi Milos, after downgrading rayshader the issue remains. 

I have solved this issue with the following workaround: ```baseshape = "circle"``` in plot_3d.

**Comment by milos-agathon** [comment]
Thank you, Luis! If you open the pull request with your changes (including the downgrade part), I'll merge it into my main branch.

**Comment by lbarqueira** [comment]
Hi Milos, I am using rstudio and I am not connected to github,. I have to follow your tutorial on using Vscode with R, because I feel more comfortable to use vscode to connect to github. As soon as I change from IDE, I will create a pull request with the changes. 
Thank you
Luis
