### ISSUE TITLE
Error rendering highquality object

### ISSUE THREAD

**Issue by lbarqueira** [milos-agathon/make-your-3d-city#3]
Hi Milos,

I have another issue while trying to render highquality object (Point 7 of your code). The following error appears:

```
Error in rayvertex::validate_mesh(mesh) : 
  !any(is.na(normals)) is not TRUE
```

Any help I would appreciate.

Thank you very much

Luis Barqueira

**Comment by milos-agathon** [comment]
Hi Luis,
It looks like you are getting this error because you are using the latest version of rayshader (see the issue here: https://github.com/tylermorganwall/rayshader/issues/289).
I'm afraid you'll have to downgrade your rayshader to the previous version.

**Comment by lbarqueira** [comment]
Thank you very much Milos, I downgraded rayshader and it works now.

**Comment by michalskop** [comment]
I ended here by searching this problem, it took me a while to find the solution, so I am dropping it here:

### How to downgrade rayshader?
1. install devtools
2. devtools::install_version("rayshader", version = "0.35.7", repos = "http://cran.r-project.org")

Always restart R (R studion)

Not all numbers/versions exist (it took me a while to realize this, I was getting errors for 0.35 or 0.35.0 or 0.35.1)

Use a small example to find the problems quickly (🇦🇩 Andorra was my friend)

**Comment by milos-agathon** [comment]
Thank you so much for your detailed response, Michal! I just posted and pinned your response on my YouTube video

**Comment by mdnahinalam** [comment]
> Thank you very much Milos, I downgraded rayshader and it works now.

kindly share the solution here, please. I'm constantly facing this error. @lbarqueira

**Comment by mdnahinalam** [comment]
Downloading package from url: http://cran.r-project.org/src/contrib/rayshader_0.35.7.tar.gz
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'http://cran.r-project.org/src/contrib/rayshader_0.35.7.tar.gz' failed
